name: jh_sharedprefs
description: "The `jh_sharedprefs` package is a utility for managing persistent storage in Flutter applications using the `shared_preferences` package. It provides a simple and efficient way to store, retrieve, update, and delete data in key-value pairs"
version: 1.0.0
homepage: https://github.com/ALI-tech-tech/jh_service_all/tree/main/packages/jh_sharedprefs
repository: https://github.com/ALI-tech-tech/jh_service_all/tree/main/packages/jh_sharedprefs
example: example/lib/main.dart

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
